# Generated by Django 4.0.2 on 2022-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Purito', 'Purito'), ('Missha', 'Missha'), ('Innistfree', 'Innistfree'), ('Isntree', 'Isntree')], max_length=200, null=True),
        ),
    ]
